[toolchain]
channel = "1.79.0-x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
]
profile = "minimal"

[toolchain.1.79.0-x86_64-unknown-linux-gnu]
components = [
    "clippy",
    "rust-src"
]

[toolchain.nightly-x86_64-unknown-linux-gnu]
components = ["rustfmt"]