array_width = 0
attr_fn_like_width = 0
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 0
brace_style = "SameLineWhere"
chain_width = 150
color = "Never"
combine_control_expr = false
comment_width = 150
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
fn_call_width = 0
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = false
doc_comment_code_block_width = 100
format_generated_files = false
generated_marker_line_search_limit = 5
format_macro_matchers = false
format_macro_bodies = false
skip_macro_invocations = ["*"]
format_strings = false
hard_tabs = false
hex_literal_case = "Preserve"
show_parse_errors = true
ignore = []
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 180
merge_derives = true
imports_granularity = "One"
newline_style = "Auto"
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = false
remove_nested_parens = false
reorder_impl_items = false
reorder_imports = true
group_imports = "One"
reorder_modules = true
short_array_element_width_threshold = 0
skip_children = false
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = false
style_edition = "2024"
where_single_line = false
wrap_comments = false