FROM rust:1.79.0
RUN \
    mkdir -p /simo_intermediary
RUN \
    rustup default 1.79.0-x86_64-unknown-linux-gnu
RUN \
    rustup toolchain install nightly-x86_64-unknown-linux-gnu
RUN \
    rustup component add --toolchain=1.79.0-x86_64-unknown-linux-gnu \
        clippy \
        rust-src
RUN \
    rustup component add --toolchain=nightly-x86_64-unknown-linux-gnu \
        rustfmt
RUN \
    git config --global --add safe.directory /simo_intermediary
ENV TZ=America/New_York
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/root
RUN \
    apt-get update && \
    apt-get upgrade -y
RUN \
    apt-get install -y \
        curl \
        build-essential \
        pkg-config \
        libudev-dev \
        llvm \
        libclang-dev \
        protobuf-compiler \
        libssl-dev
RUN \
    sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
ENV PATH=/$HOME/.local/share/solana/install/active_release/bin:$PATH